import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import LoggedIn from "./component/LoggedIn";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` ${inter.variable} antialiased`}
    >
      <body className="min-h-full">
        <AuthProvider>
          <LoggedIn />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
